Add page describing SLAs and support process
syntasso/kratix-docs pull request #79
Opened 2024-06-28 16:21 UTC by cghsystems

2024-07-01 10:35 UTC, abangser requested changes
Made a few updates/comments. Also curious about having a index page for this given there is only one piece of content. I would suggest we link straight to it until we have a second page. WDYT?

2024-07-01 10:35 UTC, abangser commented on docs/ske/04-support/00-intro.mdx
> +| **Level 3** | Release has a minor problem which can be worked round by the member of the Bank Group concerned without significant inconvenience. | Fix timeline published on roadmap |
And should this have an ack time frame?

2024-07-01 10:35 UTC, abangser commented on docs/ske/04-support/00-intro.mdx
> +Syntasso support will respond to all requests received through the official channels listed. However, community channels exist in the Kratix Slack Workspace [TODO ADD LINK] for peer-to-peer support a
missing link!

2024-07-01 10:56 UTC, cghsystems commented on docs/ske/04-support/00-intro.mdx
> +Syntasso support will respond to all requests received through the official channels listed. However, community channels exist in the Kratix Slack Workspace [TODO ADD LINK] for peer-to-peer support a
Goo spot. Added.

2024-07-02 08:46 UTC, abangser approved these changes
just one errant capitalisation. otherwise renders well and looks great 💅

2024-07-02 08:46 UTC, abangser commented on docs/ske/00-support.mdx
> +| **Level 1** | Release is unusable or substantially inoperable as a result of an incident | Response within 4 business Hours, Fix within 5 business days |
```suggestion
| **Level 1** | Release is unusable or substantially inoperable as a result of an incident | Response within 4 business hours, Fix within 5 business days |
```

2024-07-02 13:57 UTC, merged